fixing potential LOG.ERROR after latest memory optimization...
Below is the cause of a bunch of failing test cases. Had a call with
Marc and we can't fully explain. Thinking is that due to the latest
changes of the "FromListIterator", which is now potentially reading from
disc, a buffer is GC'ed and attempting to swap to disc. The buffer is
certainly associated with a test case that had already run (as also seen
below). We are not 100% certain why this hasn't happened so ofter prior
the change. It could be due to the fact that we keep a 'hard' buffer
reference in the list iterator whereas previously it was a non-static
inner class, which never used "Buffer.this" -- so potentially optimized
by the compiler?

MacOS10.14 / Run tests MacOS10.14 /
testflowsMaster.mining.logisticRegression.bug4439.assertions_on.log
messages

Failing for the past 1 build (Since Unstable#1400 )
Took 0 ms.
add description
Error Message
Unexpected ERROR logged: Temp folder
"/Users/jenkins/slave/workspace/workflow-tests_master@2/tmp/knime_temp/knime_test_AP_10367_R101795"
does not exist (associated with node context "Random Forest Learner
0:211:85 (EXECUTED)") - using fallback temp folder
("/Users/jenkins/slave/workspace/workflow-tests_master@2/tmp/knime_temp"
Stacktrace
junit.framework.AssertionFailedError: Unexpected ERROR logged: Temp
folder "/Users/jenkins/slave/workspace/workflow-tests_master@2/tmp/knime_temp/knime_test_AP_10367_R101795"
does not exist (associated with node context "Random Forest Learner
0:211:85 (EXECUTED)") - using fallback temp folder
("/Users/jenkins/slave/workspace/workflow-tests_master@2/tmp/knime_temp"
	at org.knime.testing.core.ng.WorkflowLogMessagesTest.checkLogMessages(WorkflowLogMessagesTest.java:207)
	at org.knime.testing.core.ng.WorkflowLogMessagesTest.run(WorkflowLogMessagesTest.java:131)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:241)