AP-13925: Catch NoClassDefFoundError instead of Exception
AP-13925 (PortTypeRegistry fails ungracefully when encountering
erroneous port types among all available port types)