fixing unreported bug:
2013-04-12 20:50:34,306 DEBUG KNIME Sync Exec Dispatcher-1 SyncExecQueueDispatcher : Uncaught exception while queuing events into main thread
org.eclipse.swt.SWTException: Failed to execute runnable (java.util.ConcurrentModificationException)
        at org.eclipse.swt.SWT.error(SWT.java:4282)
        at org.eclipse.swt.SWT.error(SWT.java:4197)
        at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:196)
        at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
        at org.eclipse.swt.widgets.Display.syncExec(Display.java:4330)
        at org.knime.workbench.ui.SyncExecQueueDispatcher$2.run(SyncExecQueueDispatcher.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.util.ConcurrentModificationException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
        at java.util.TreeMap$KeyIterator.next(TreeMap.java:1169)
        at org.knime.core.node.workflow.Workflow.getSourceNodes(Workflow.java:487)
        at org.knime.core.node.workflow.Workflow.createBreadthFirstSortedList(Workflow.java:317)
        at org.knime.core.node.workflow.WorkflowManager.fillLinkedMetaNodesList(WorkflowManager.java:5485)
        at org.knime.core.node.workflow.WorkflowManager.fillLinkedMetaNodesList(WorkflowManager.java:5493)
        at org.knime.core.node.workflow.WorkflowManager.fillLinkedMetaNodesList(WorkflowManager.java:5493)
        at org.knime.core.node.workflow.WorkflowManager.getLinkedMetaNodes(WorkflowManager.java:5479)
        at org.knime.workbench.editor2.actions.CheckUpdateMetaNodeLinkAllAction.getMetaNodesToCheck(CheckUpdateMetaNodeLinkAllAction.java:94)
        at org.knime.workbench.editor2.actions.CheckUpdateMetaNodeLinkAction.calculateEnabled(CheckUpdateMetaNodeLinkAction.java:159)
        at org.eclipse.gef.ui.actions.WorkbenchPartAction.isEnabled(WorkbenchPartAction.java:123)
        at org.knime.workbench.editor2.actions.delegates.AbstractEditorAction.selectionChanged(AbstractEditorAction.java:155)
        at org.eclipse.ui.internal.PluginAction.refreshEnablement(PluginAction.java:206)
        at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:277)
        at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:289)
        at org.eclipse.gef.ui.parts.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:247)
        at org.eclipse.gef.ui.parts.AbstractEditPartViewer$1.run(AbstractEditPartViewer.java:131)
        at org.eclipse.gef.SelectionManager.fireSelectionChanged(SelectionManager.java:144)
        at org.eclipse.gef.SelectionManager.setSelection(SelectionManager.java:279)
        at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setSelection(AbstractEditPartViewer.java:751)
        at org.knime.workbench.editor2.actions.delegates.AbstractEditorAction$SelectionRunnable.run(AbstractEditorAction.java:177)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3563)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3212)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:173)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:388)
        at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1029)
        at org.knime.workbench.explorer.view.actions.QuickformExecuteWizard.runRun(QuickformExecuteWizard.java:266)
        at org.knime.workbench.explorer.view.actions.QuickformExecuteWizard.stepExecution(QuickformExecuteWizard.java:177)
        at org.knime.workbench.explorer.view.actions.QuickformExecuteWizard.getNextPage(QuickformExecuteWizard.java:126)
        at org.eclipse.jface.wizard.WizardPage.getNextPage(WizardPage.java:172)
        at org.knime.workbench.explorer.view.actions.QuickformExecuteWizardPage.getNextPage(QuickformExecuteWizardPage.java:129)
        at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:908)
        at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:428)
        at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)