deleted dead code (was disable by static final constant)
... and it cause random test case failures, such as:
junit.framework.AssertionFailedError: Firing of the trigger should not
have happened yet.
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at junit.framework.TestCase.assertFalse(TestCase.java:208)
	at org.knime.core.util.RetriggerableDelayedRunnableTest.testEarlyRetrigger(RetriggerableDelayedRunnableTest.java:79)