increased test timeout, failed on slow mac in test system
... usual run time is ~1-1.2sec on Mac but this time it failed:


MacOS10.11 / Run tests MacOS10.11 /
org.knime.core.node.workflow.BugAP6262_FileStoresInPortObjectCell.testExecute

Failing for the past 1 build (Since Unstable#867 )
Took 3.5 sec.
add description
Error Message
test timed out after 3000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 3000
milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.knime.core.node.workflow.WorkflowTestCase.waitWhile(WorkflowTestCase.java:445)
	at org.knime.core.node.workflow.WorkflowTestCase.waitWhileNodeInExecution(WorkflowTestCase.java:405)
	at org.knime.core.node.workflow.WorkflowTestCase.waitWhileInExecution(WorkflowTestCase.java:396)
	at org.knime.core.node.workflow.WorkflowTestCase.executeAllAndWait(WorkflowTestCase.java:356)
	at org.knime.core.node.workflow.BugAP6262_FileStoresInPortObjectCell.testExecute(BugAP6262_FileStoresInPortObjectCell.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)