catch throwable instead of error when no display access (in SGE execution), stack trace was 2012-12-06 11:47:17,999 DEBUG main WorkflowPersistorVersion200 : Unable to load node with ID suffix 5 into workflow, skipping it: Could not initialize class sun.awt.X11.XToolkit java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit         at java.lang.Class.forName0(Native Method)         at java.lang.Class.forName(Class.java:186)         at java.awt.Toolkit$2.run(Toolkit.java:870)         at java.security.AccessController.doPrivileged(Native Method)         at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:862)         at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:608)         at org.knime.core.node.Node.<clinit>(Node.java:231)         at org.knime.core.node.workflow.SingleNodeContainerPersistorVersion1xx.preLoadNodeContainer(SingleNodeContainerPersistorVersion1xx.java:314)